### ISSUE TITLE
mix format fails when running from Emacs

### ISSUE THREAD

**Issue by wittjosiah** [asdf-vm/asdf-elixir#62] opened 2019-05-05 17:11 UTC
### Background

macOS 10.14.4
erlang 21.3.4
elixir 1.8.1

I'm using spacemacs with the elixir package installed.

### Expected behaviour

Running elixir-format emacs command from emacs-elixir will format the current file and on save hook will also format the file.

### Actual behaviour

Running elixir-format hook in emacs-elixir results in the following error message being displayed:

```
** (SyntaxError) /Users/josiah/.asdf/shims/mix:3: syntax error before: '.'
    (elixir) lib/code.ex:767: Code.require_file/2
```

The on save hook fails silently.

### Other Information

This problem only seems to crop up when elixir is installed with asdf, when I had elixir installed with brew I had no problems.

Any help pointing me in the right direction is much appreciated :)

**Comment by danhper** [comment] 2019-05-06 08:23
The issue is that `elixir-format` runs `elixir /path/to/mix format` and not `/path/to/mix format`.
https://github.com/elixir-editors/emacs-elixir/blob/master/elixir-format.el
I'm not exactly sure why, but it might be worth asking in their repository.
When using `asdf`, `mix` executable is a shell script, and therefore, it fails.

Fortunately, it seems that they get the `mix` path using a function called `elixir-format--mix-executable`, so while waiting for a more permanent fix, you can override this function. Try adding the following to your `~/.emacs` (or `~/.spacemacs` if you use Spacemacs I suppose)

```lisp
(eval-after-load "elixir-mode"
  '(defun elixir-format--mix-executable ()
     (string-trim-right (shell-command-to-string "asdf which mix"))))
```

This runs after `elixir-mode`, which provides `elixir-format`, has been loaded, and overrides `elixir-format--mix-executable` to return the result of `asdf which mix` instead of trying to look for `mix` in the path.

I'm not really sure there is much we can do about it on our side, as this is how shims work, but I will leave this open in case somebody wants to propose a solution.

**Comment by wittjosiah** [comment] 2019-05-06 21:32
Thanks @danhper! That config seems to have solved it for me 😄 

As you mentioned I can leave this open in case anyone wants to propose an alternative solution, but the suggested workaround does seem to work for me if anyone else runs into this issue.

**Comment by MainShayne233** [comment] 2019-06-06 19:14
Just to add, I was able to solve this problem by manually updating my `~/.asdf/shims/mix` to be:

```elixir
#!/usr/bin/env elixir
# asdf-plugin: elixir 1.7.3
# asdf-plugin: elixir 1.8.2
Mix.start
Mix.CLI.main
```

(of course, the lines about Elixir versions are personal to my file)

**Comment by danhper** [comment] 2019-06-22 11:34
@MainShayne233 Thanks for sharing this. Actually you do not really need the `asdf-plugin` lines in this case.
I think we should probably make this the default shim for `mix` because this will work with any version and would avoid such issues.

**Comment by darylwalsh** [comment] 2019-07-18 02:49
I was getting the exact same error initially running mix format in vim/neovim with the vim-mix-format plugin. 
Converting ~/.asdf/shims/mix to the suggested fix above indeed allowed mix format to run properly from inside neovim...however the mix CLI commands outside vim started erroring out.   

During install of vim-mix-format I defined g:mix_format_elixir_bin_path to point to the asdf shim directory.
 
Commenting out/removing g:mix_format_elixir_bin_path in the .vimrc / init.vim file && reverting ~/.asdf/shims/mix to its initial configuration now allows mix format to run properly inside vim/nvim as well as on the standard OS CLI. That is, took out Mix.start and Mix.CLI.main fix and  put back the ' exec /path/to/asdf exec "mix" "$@"  ' line . 

If you have a similar bin path variable inside emacs config, maybe try removing that and rely on emacs picking up the mix executable from the OS or an env var.

**Comment by Stratus3D** [comment] 2019-07-18 13:58
I'm going to close this issue since I don't think there are any issues with asdf and asdf-elixir that are contributing to this problem. Other programs should simply expect commands like `elixir`, `mix` and `iex` to be on the path. Programs should not specify the paths to commands.

**Closed by Stratus3D** 2019-07-18 13:58 UTC

**Comment by danhper** [comment] 2019-07-19 11:29
> .however the mix CLI commands outside vim started erroring out.

What errors did you get?
I have been trying out the shim proposed by @MainShayne233 and did not have any issue.

I will reopen this because at realized that in the current state `iex -S mix`, which is a very common thing to use when using Elixir, fails.

```
$ iex -S mix
Erlang/OTP 22 [erts-10.4.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

** (SyntaxError) /home/daniel/.asdf/shims/mix:3: syntax error before: '.'
    (elixir) lib/code.ex:767: Code.require_file/2
```

If we can confirm that the following shim works without any issue, I think it would be worth adding it.

```
#!/usr/bin/env elixir

Mix.start
Mix.CLI.main
```

I have been using it for a month or so and did not run into any particular issue so I would like to know what happened on @darylwalsh setup.

**Comment by matisnape** [comment] 2019-12-12 14:57
I have similar issue
```
iex -S mix phoenix.server
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

** (SyntaxError) /usr/local/opt/asdf/shims/mix:3: syntax error before: "$@"
    (elixir) lib/code.ex:767: Code.require_file/2
```

**Comment by Stratus3D** [comment] 2019-12-12 17:49
@matisnape what version of asdf are you running? That command works for me on the latest version of asdf and asdf-elixir.

**Comment by robsonpeixoto** [comment] 2021-03-21 22:31
@Stratus3D, same problem here.

```
~/tmp/example1 12s
❯ iex -S mix phx.server
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

** (SyntaxError) /Users/robinho/.asdf/shims/mix:4:46: syntax error before: "$@"
    (elixir 1.11.4) lib/code.ex:931: Code.require_file/2

~/tmp/example1
❯ asdf current elixir
elixir          system          /Users/robinho/.tool-versions
```

**Comment by Stratus3D** [comment] 2021-04-15 15:33
@robsonpeixoto , again, what version of asdf are you running? You can just paste the output of `asdf info`.

**Comment by robsonpeixoto** [comment] 2021-04-15 16:09
Sorry:
```
❯ asdf info
OS:
Darwin updated6.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin20.1.0)

ASDF VERSION:
v0.8.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf

ASDF INSTALLED PLUGINS:
elixir                       git@github.com:asdf-vm/asdf-elixir.git
erlang                       git@github.com:asdf-vm/asdf-erlang.git
java                         git@github.com:halcyon/asdf-java.git
maven                        git@github.com:halcyon/asdf-maven.git
python                       git@github.com:danhper/asdf-python.git
terraform                    git@github.com:Banno/asdf-hashicorp.git
terragrunt                   git@github.com:lotia/asdf-terragrunt.git
```

**Comment by Stratus3D** [comment] 2021-04-15 17:03
Did you try running `asdf reshim` @robsonpeixoto ? Does this issue occur outside of emacs (e.g. in Bash)?

**Comment by robsonpeixoto** [comment] 2021-04-15 17:43
Yep, this issue occur on zsh:
```
❯ asdf reshim

❯ iex -S mix phx.server
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

** (SyntaxError) /Users/robinho/.asdf/shims/mix:4:46: syntax error before: "$@"
    (elixir 1.11.4) lib/code.ex:931: Code.require_file/2

❯ asdf current elixir
elixir          system          /Users/robinho/.tool-versions

❯ asdf which iex
/usr/local/bin/iex

```

**Comment by Stratus3D** [comment] 2021-04-15 19:01
Strange. I do not encounter this issue and I'm running the same version of asdf, and a similar version of OSX and Zshell.

**Comment by Stratus3D** [comment] 2021-04-15 19:02
Did you try updating the plugin? `asdf plugin-update elixir`?

**Comment by robsonpeixoto** [comment] 2021-04-15 19:25
Now is working:

```
❯ asdf plugin-remove elixir

❯ asdf plugin-add elixir
updating plugin repository...
HEAD is now at 1040bc8 Merge pull request #388 from asdf-vm/asdf-poetry

❯ iex -S mix phx.server
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Compiling 2 files (.ex)
....
```
